<?php

//  $Id$

/*
 *
 * @file
 *
 */

$itunes_categories = array(
    'Arts' => array(
      'Arts' => 'Arts (general)',
      'Arts:Design' => 'Design',
      'Arts:Fashion & Beauty' => 'Fashion & Beauty',
      'Arts:Food' => 'Food',
      'Arts:Literature' => 'Literature',
      'Arts:Performing Arts' => 'Performing Arts',
      'Arts:Visual Arts' => 'Visual Arts',
    ), 
    'Business' => array(
      'Business' => 'Business (general)',
      'Business:Business News' => 'Business News',
      'Business:Careers' => 'Careers',
      'Business:Investing' => 'Investing',
      'Business:Management & Marketing' => 'Management & Marketing',
      'Business:Shopping' => 'Shopping',
    ),
    'Comedy' => array(
      'Comedy' => 'Comedy'
    ),    
    'Education' => array(
      'Education' => 'Education (general)',
      'Education:Education Technology' => 'Education Technology',
      'Education:Higher Education' => 'Higher Education',
      'Education:K-12' => 'K-12',
      'Education:Language Courses' => 'Language Courses',
      'Education:Training' => 'Training',
    ),
    'Games & Hobbies' => array(
      'Games & Hobbies' => 'Games & Hobbies (general)',
      'Games & Hobbies:Automotive' => 'Automotive',
      'Games & Hobbies:Aviation' => 'Aviation',
      'Games & Hobbies:Hobbies' => 'Hobbies',
      'Games & Hobbies:Other Games' => 'Other Games',
      'Games & Hobbies:Video Games' => 'Video Games',
    ),
    'Government & Organizations' => array(
      'Government & Organizations' => 'Government & Organizations (general)',
      'Government & Organizations:Local' => 'Local',
      'Government & Organizations:National' => 'National',
      'Government & Organizations:Non-Profit' => 'Non-Profit',
      'Government & Organizations:Regional' => 'Regional',
    ),
    'Health' => array(
      'Health' => 'Health (general)',
      'Health:Alternative Health' => 'Alternative Health',
      'Health:Fitness & Nutrition' => 'Fitness & Nutrition',
      'Health:Self-Help' => 'Self-Help',
      'Health:Sexuality' => 'Sexuality',
    ),
    'Kids & Family' => array(
      'Kids & Family' => 'Kids & Family',
    ),    
    'Music' => array(
      'Music' => 'Music',
    ),    
    'News & Politics' => array(
      'News & Politics' => 'News & Politics',
    ),    
    'Religion & Spirituality' => array(
      'Religion & Spirituality' => 'Religion & Spirituality (general)',
      'Religion & Spirituality:Buddhism' => 'Buddhism',
      'Religion & Spirituality:Christianity' => 'Christianity',
      'Religion & Spirituality:Hinduism' => 'Hinduism',
      'Religion & Spirituality:Islam' => 'Islam',
      'Religion & Spirituality:Judaism' => 'Judaism',
      'Religion & Spirituality:Other' => 'Other',
      'Religion & Spirituality:Spirituality' => 'Spirituality',
    ),    
    'Science & Medicine' => array(
      'Science & Medicine' => 'Science & Medicine (general)',
      'Science & Medicine:Medicine' => 'Medicine',      
      'Science & Medicine:Natural Sciences' => 'Natural Sciences',
      'Science & Medicine:Social Sciences' => 'Social Sciences',
    ),
    'Society & Culture' => array(
      'Society & Culture' => 'Society & Culture (general)',
      'Society & Culture:History' => 'History',
      'Society & Culture:Personal Journals' => 'Personal Journals',
      'Society & Culture:Philosophy' => 'Philosophy',
      'Society & Culture:Places & Travel' => 'Places & Travel',
    ),
    'Sports & Recreation' => array(
      'Sports & Recreation' => 'Sports & Recreation (general)',
      'Sports & Recreation:Amateur' => 'Amateur',
      'Sports & Recreation:College & High School' => 'College & High School',
      'Sports & Recreation:Outdoor' => 'Outdoor',
      'Sports & Recreation:Professional' => 'Professional',
    ),
    'Technology' => array(
      'Technology' => 'Technology (general)',
      'Technology:Gadgets' => 'Gadgets',
      'Technology:Tech News' => 'Tech News',
      'Technology:Podcasting' => 'Podcasting',
      'Technology:Software How-To' => 'Software How-To',
    ),
    'TV & Film' => array(
      'TV & Film' => 'TV & Film',
    ),
  );
